import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from 'sonner'
import { ClerkProvider } from '@clerk/nextjs'
import ReduxProviders from "@/lib/providers/providers";
import NavbarDashboard from "@/components/global/navbar/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body className={inter.className}>
        <ReduxProviders>
          <NavbarDashboard/>
          <div className="mt-16">
          {children}
          </div>
        </ReduxProviders>
        <Toaster/>
      </body>
    </html>
    </ClerkProvider>
  );
}
